import matplotlib
matplotlib.use('Agg')  # Headless backend — must be before any other matplotlib import

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import io
import datetime
from fpdf import FPDF


class IncidentReportPDF(FPDF):
    def header(self):
        # Header bar
        self.set_fill_color(15, 10, 30)
        self.rect(0, 0, 210, 18, 'F')
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(180, 90, 255)
        self.set_y(4)
        self.cell(0, 10, 'CrowdSense - AI Incident Report', align='C')
        self.set_text_color(200, 200, 200)
        self.ln(14)

    def footer(self):
        self.set_y(-13)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(130, 130, 130)
        self.cell(
            0, 10,
            f'Generated by CrowdSense AI  |  Page {self.page_no()}  |  {datetime.datetime.now().strftime("%Y-%m-%d")}',
            align='C'
        )

    def section_title(self, title: str):
        self.set_fill_color(30, 20, 55)
        self.set_text_color(180, 90, 255)
        self.set_font('helvetica', 'B', 12)
        self.cell(0, 9, f'  {title}', fill=True, new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(220, 220, 220)
        self.ln(2)


class ReportGenerator:
    def __init__(self):
        pass

    # ── Chart generators ──────────────────────────────────────────────────────

    def _density_chart(self, density_history):
        """Line chart of crowd density over processed frames."""
        fig, ax = plt.subplots(figsize=(8, 3))
        fig.patch.set_facecolor('#0f1015')
        ax.set_facecolor('#0f1015')

        x = list(range(len(density_history)))
        ax.plot(x, density_history, color='#aa3bff', linewidth=2, zorder=3)
        ax.fill_between(x, density_history, alpha=0.15, color='#aa3bff')

        # Danger threshold line
        if max(density_history, default=0) > 15:
            ax.axhline(y=15, color='#ef4444', linestyle='--', linewidth=1, alpha=0.7, label='Danger threshold')

        ax.set_title('Crowd Density Over Time', color='#e2e8f0', fontsize=11, pad=8)
        ax.set_xlabel('Processed Frame Index', color='#9ca3af', fontsize=9)
        ax.set_ylabel('Total People Count', color='#9ca3af', fontsize=9)
        ax.tick_params(colors='#9ca3af')
        for spine in ax.spines.values():
            spine.set_edgecolor('#2d2d3d')
        ax.grid(True, linestyle='--', alpha=0.3, color='#4b5563')

        buf = io.BytesIO()
        plt.savefig(buf, format='PNG', bbox_inches='tight', dpi=120, facecolor='#0f1015')
        buf.seek(0)
        plt.close(fig)
        return buf

    def _alert_type_chart(self, alerts):
        """Bar chart of alert type distribution."""
        type_counts = {}
        for a in alerts:
            t = a.get('type', 'UNKNOWN')
            type_counts[t] = type_counts.get(t, 0) + 1

        if not type_counts:
            return None

        fig, ax = plt.subplots(figsize=(6, 2.5))
        fig.patch.set_facecolor('#0f1015')
        ax.set_facecolor('#0f1015')

        labels = list(type_counts.keys())
        values = list(type_counts.values())
        colors = ['#ef4444' if 'DENSITY' in l or 'FREEZE' in l else '#f59e0b' for l in labels]

        bars = ax.barh(labels, values, color=colors, height=0.5)
        ax.set_title('Alert Type Distribution', color='#e2e8f0', fontsize=10, pad=6)
        ax.tick_params(colors='#9ca3af', labelsize=8)
        for spine in ax.spines.values():
            spine.set_edgecolor('#2d2d3d')
        ax.grid(axis='x', linestyle='--', alpha=0.3, color='#4b5563')

        buf = io.BytesIO()
        plt.savefig(buf, format='PNG', bbox_inches='tight', dpi=110, facecolor='#0f1015')
        buf.seek(0)
        plt.close(fig)
        return buf

    # ── Main PDF builder ──────────────────────────────────────────────────────

    def generate_pdf(self, video_name, duration, alerts, density_history, zone_summary):
        pdf = IncidentReportPDF()
        pdf.set_auto_page_break(auto=True, margin=18)
        pdf.add_page()

        # ── Cover metadata ────────────────────────────────────────────────────
        pdf.set_font('helvetica', 'B', 16)
        pdf.set_text_color(230, 230, 255)
        pdf.cell(0, 10, 'Crowd Intelligence Incident Report', new_x='LMARGIN', new_y='NEXT')
        pdf.ln(2)

        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(160, 160, 180)
        pdf.cell(0, 7, f'Source File:  {video_name}', new_x='LMARGIN', new_y='NEXT')
        pdf.cell(0, 7, f'Analysis Duration:  {duration}', new_x='LMARGIN', new_y='NEXT')
        pdf.cell(0, 7, f'Generated:  {datetime.datetime.now().strftime("%A, %d %B %Y  %H:%M:%S")}', new_x='LMARGIN', new_y='NEXT')
        pdf.cell(0, 7, f'Total Alerts:  {len(alerts)}', new_x='LMARGIN', new_y='NEXT')
        total_people = max(density_history) if density_history else 0
        pdf.cell(0, 7, f'Peak Crowd Size:  {total_people} people', new_x='LMARGIN', new_y='NEXT')
        pdf.ln(6)

        # ── Density chart ─────────────────────────────────────────────────────
        pdf.section_title('Section 1 - Crowd Density Timeline')
        if density_history:
            try:
                chart_buf = self._density_chart(density_history)
                pdf.image(chart_buf, w=175, x=17, h=55)
                pdf.ln(4)
            except Exception as e:
                pdf.set_font('helvetica', 'I', 9)
                pdf.set_text_color(150, 150, 150)
                pdf.cell(0, 8, f'[Chart unavailable: {e}]', new_x='LMARGIN', new_y='NEXT')
        else:
            pdf.set_font('helvetica', 'I', 9)
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 8, 'No density data recorded for this session.', new_x='LMARGIN', new_y='NEXT')
        pdf.ln(4)

        # ── Alert type distribution chart ─────────────────────────────────────
        if alerts:
            pdf.section_title('Section 2 - Alert Distribution')
            try:
                alert_chart_buf = self._alert_type_chart(alerts)
                if alert_chart_buf:
                    pdf.image(alert_chart_buf, w=130, x=40, h=45)
                    pdf.ln(4)
            except Exception:
                pass

        # ── AI Alert Narratives ───────────────────────────────────────────────
        pdf.section_title('Section 3 - AI Alert Narratives')
        pdf.set_font('helvetica', '', 10)

        if not alerts:
            pdf.set_text_color(120, 180, 120)
            pdf.cell(0, 8, 'No significant incidents were detected during this session.', new_x='LMARGIN', new_y='NEXT')
        else:
            for i, alert in enumerate(alerts[:30]):  # cap at 30 to prevent giant PDFs
                sev = alert.get('severity', 'LOW')
                atype = alert.get('type', 'UNKNOWN')
                msg = alert.get('message', '')
                ts = alert.get('timestamp', '')
                frame_idx = alert.get('frame_idx', '?')

                # Severity colour
                if sev == 'HIGH':
                    pdf.set_fill_color(60, 20, 20)
                    pdf.set_text_color(252, 165, 165)
                elif sev == 'MEDIUM':
                    pdf.set_fill_color(50, 35, 10)
                    pdf.set_text_color(253, 211, 77)
                else:
                    pdf.set_fill_color(20, 35, 60)
                    pdf.set_text_color(147, 197, 253)

                pdf.set_font('helvetica', 'B', 10)
                label = f'  [{i+1}] {atype}  |  Severity: {sev}  |  Frame: {frame_idx}  |  {ts}'
                pdf.cell(0, 8, label, fill=True, new_x='LMARGIN', new_y='NEXT')

                pdf.set_font('helvetica', '', 9)
                pdf.set_text_color(210, 210, 210)
                pdf.set_fill_color(22, 22, 35)
                pdf.multi_cell(0, 7, f'  {msg}', fill=True)
                pdf.ln(2)

        pdf.ln(4)

        # ── Zone summary table ────────────────────────────────────────────────
        pdf.section_title('Section 4 - Zone-wise Risk Summary')

        # Only show zones that had activity
        active_zones = [z for z in zone_summary if z.get('max_density', 0) > 0]

        if not active_zones:
            pdf.set_font('helvetica', 'I', 9)
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 8, 'No zone activity detected.', new_x='LMARGIN', new_y='NEXT')
        else:
            # Table header
            pdf.set_font('helvetica', 'B', 9)
            pdf.set_fill_color(35, 20, 60)
            pdf.set_text_color(180, 90, 255)
            pdf.cell(25, 8, 'Zone ID', border=1, fill=True)
            pdf.cell(35, 8, 'Max Density', border=1, fill=True)
            pdf.cell(35, 8, 'Row', border=1, fill=True)
            pdf.cell(35, 8, 'Column', border=1, fill=True)
            pdf.cell(60, 8, 'Risk Level', border=1, fill=True, new_x='LMARGIN', new_y='NEXT')

            pdf.set_font('helvetica', '', 9)
            for zone in active_zones[:50]:  # cap rows
                zid = zone.get('id', 0)
                density = zone.get('max_density', 0)
                row = zid // 10
                col = zid % 10
                risk = 'CRITICAL' if density > 15 else ('HIGH' if density > 10 else ('MEDIUM' if density > 5 else 'LOW'))

                if risk == 'CRITICAL':
                    pdf.set_text_color(252, 165, 165)
                elif risk == 'HIGH':
                    pdf.set_text_color(252, 165, 165)
                elif risk == 'MEDIUM':
                    pdf.set_text_color(253, 211, 77)
                else:
                    pdf.set_text_color(134, 239, 172)

                pdf.cell(25, 7, str(zid), border=1)
                pdf.cell(35, 7, str(density), border=1)
                pdf.cell(35, 7, str(row), border=1)
                pdf.cell(35, 7, str(col), border=1)
                pdf.cell(60, 7, risk, border=1, new_x='LMARGIN', new_y='NEXT')

        pdf.ln(8)

        # ── Action checklist ──────────────────────────────────────────────────
        pdf.section_title('Section 5 - Recommended Action Checklist')
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(210, 210, 220)

        actions = [
            'Dispatch ground staff to all zones rated HIGH or CRITICAL.',
            'Open all auxiliary exit routes immediately.',
            'Halt new entries to congested zones until density drops.',
            'Broadcast directional crowd-flow instructions via PA system.',
            'Alert emergency response teams to be on standby.',
            'Review CCTV footage for zones with Density Surge events.',
            'Document incident timeline for post-event review.',
        ]
        for action in actions:
            pdf.cell(8, 8, '')
            pdf.set_text_color(180, 90, 255)
            pdf.cell(6, 8, '>')
            pdf.set_text_color(210, 210, 220)
            pdf.cell(0, 8, action, new_x='LMARGIN', new_y='NEXT')

        # Return as bytes (fpdf2 output() returns bytearray by default)
        try:
            return bytes(pdf.output())
        except Exception as e:
            print(f"PDF Output Error: {e}")
            return b""
